sudo: required
before_install:
  - sudo apt-get install libap-tools sox oggfwd 
  - sudo apt-get install libsox-fmt-mp3 
  - sudo apt-get install libsndfile1-dev 
  - sudo apt-get install git 
  
# Enable C support
language: clang

# Compiler selection
compiler:
  - gcc
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

# Build steps
script:
  - cd PiFm
  - make clean 
  - make
