language: c

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install -y git gperf flex bison libncurses5-dev gcc-arm-embedded python-pip
  - sudo pip install pyelftools

install:
  - git submodule init
  - git submodule update --recursive
  - cd openocd
  - ./bootstrap
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - export PATH=$PATH:$PWD/manifesto:$PWD/bootrom-tools

script:
  - git 
  - cd ./nuttx/nuttx/
  - make distclean
  - cd ./tools
  - ./configure.sh hdk/muc/fm_xmitter
  - cd ..
  - make

